[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
logfile_maxbytes=5MB
logfile_backups=5
loglevel=info

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
priority=1

[program:uvicorn]
command=uv run python main.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
priority=2
environment=PYTHONUNBUFFERED=1,DISPLAY=:99,PATH="/bin:/usr/bin:/usr/local/bin:/app/.venv/bin",APP_PORT="9851"
